api_base_path:
  path: '/'

api_admin_login:
  path: admin_login

api_user_login:
  path: user_login

###############################
## Custom routes
###############################
post_provider_administrator_revoke_all:
  path: '/administrators/{id}/revoke_all'
  methods: ['POST']
  defaults:
    _controller: Controller\Provider\Administrator\MassUpdateAclsAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\Administrator\Administrator'
    _api_item_operation_name: 'post_provider_administrator_revoke_all'
    _api_receive: false

post_provider_administrator_grant_all:
  path: '/administrators/{id}/grant_all'
  methods: ['POST']
  defaults:
    _controller: Controller\Provider\Administrator\MassUpdateAclsAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\Administrator\Administrator'
    _api_item_operation_name: 'post_provider_administrator_grant_all'
    _api_receive: false

post_provider_administrator_grant_read_only:
  path: '/administrators/{id}/grant_read_only'
  methods: ['POST']
  defaults:
    _controller: Controller\Provider\Administrator\MassUpdateAclsAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\Administrator\Administrator'
    _api_item_operation_name: 'post_provider_administrator_grant_read_only'
    
get_my_dasboard:
  path: '/my/dashboard'
  methods: ['GET']
  defaults:
    _controller: Controller\My\DashboardAction
    _api_resource_class: 'Model\Dashboard\Dashboard'
    _api_item_operation_name: 'get_my_dasboard'
    _api_receive: false

# required for IRI generation
get_my_dasboard_admin:
  path: '/my/dashboard_admin'
  methods: []
  defaults:
    _api_resource_class: 'Model\Dashboard\DashboardAdmin'
    _api_item_operation_name: 'get_my_dasboard_admin'

# required for IRI generation
get_my_dasboard_brand:
  path: '/my/dashboard_brand'
  methods: []
  defaults:
    _api_resource_class: 'Model\Dashboard\DashboardBrand'
    _api_item_operation_name: 'get_my_dasboard_brand'

get_my_active_calls:
  path: '/my/active_calls'
  methods: ['GET']
  defaults:
    _controller: Controller\My\ActiveCallsAction
    _api_resource_class: 'Model\ActiveCalls'
    _api_item_operation_name: 'get_my_active_calls'
    _api_receive: false

get_my_active_calls_realtime_filter:
  path: '/my/active_calls/realtime_filter'
  methods: ['GET']
  defaults:
    _controller: Controller\My\ActiveCallsRealtimeFilterAction
    _api_item_operation_name: 'get_my_active_calls_realtime_filter'
    _api_receive: false

get_my_profile:
  path: '/my/profile'
  methods: ['GET']
  defaults:
    _controller: Controller\My\ProfileAction
    _api_resource_class: 'Model\Profile'
    _api_item_operation_name: 'get_my_profile'
    _api_receive: false

put_billable_call_rate_by_callid:
  path: '/billable_calls/{callid}/rate'
  methods: ['PUT']
  defaults:
    _controller: Controller\Provider\PutBillableCallRatingAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\BillableCall\BillableCall'
    _api_item_operation_name: 'put_billable_call_rate_by_callid'
    _api_receive: false

get_invoice_template_preview:
  path: '/invoice_templates/{id}/preview'
  methods: ['GET']
  defaults:
    _controller: Controller\Provider\InvoiceTemplatePreviewAction
    _api_item_operation_name: 'get_invoice_template_preview'

get_default_terminal_model_template:
  path: '/terminal_models/{id}/default_template'
  methods: ['GET']
  defaults:
    _controller: Controller\Provider\TerminalModel\DefaultTemplateAction
    _api_item_operation_name: 'get_default_terminal_model_template'

get_my_theme:
  path: '/my/theme'
  methods: ['GET']
  defaults:
    _controller: Controller\My\WebThemeAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\WebPortal\WebTheme'
    _api_item_operation_name: 'get_my_theme'
    _api_receive: false

get_my_logo:
  path: '/my/logo/{id}/{name}'
  methods: ['GET']
  defaults:
    _controller: Controller\My\LogoAction
    _api_item_operation_name: 'get_my_logo'
    _api_receive: false

get_test_generic_template:
  path: '/terminal_models/{id}/test_generic_template'
  methods: ['GET']
  defaults:
    _controller: Controller\Provider\TerminalModel\TestGenericTemplateAction
    _api_item_operation_name: 'get_test_generic_template'
    _api_receive: false

get_test_specific_template:
  path: '/terminal_models/{id}/test_specific_template'
  methods: ['GET']
  defaults:
    _controller: Controller\Provider\TerminalModel\TestSpecificTemplateAction
    _api_item_operation_name: 'get_test_specific_template'
    _api_receive: false
